### ISSUE TITLE
Stray end tag

### ISSUE THREAD

**Issue by AhmedSafi97** [GSG-G9/MOYA-R--portfolio#20]
https://github.com/GSG-G9/MOYA-R--portfolio/blob/b7315896094eb11b143b4c8b1e3961759db10acc/index.html#L56

Forgetting to write an end tag or writing it twice is a common mistake when writing HTML, this [markup validator](https://validator.w3.org/) will help you catch these errors and validate your html code.

**Comment by Ahmed-aed** [comment]
line 31 &line56  end tag </header> repatied
