### ISSUE TITLE
resolving Git conflicts 

### ISSUE THREAD

**Issue by AhmedSafi97** [GSG-G9/MOYA-R--portfolio#21]
https://github.com/GSG-G9/MOYA-R--portfolio/blob/b7315896094eb11b143b4c8b1e3961759db10acc/index.html#L82-L103

I admit it, resolving conflicts can be confusing sometimes. So, whenever a conflict arises take your time to resolve it carefully and make sure everything resolved and work properly. 

I stumbled on [this article](https://medium.com/better-programming/how-to-resolve-git-conflicts-faster-and-more-easily-in-your-favorite-ide-9d2984283a79), I hope it would help you to build your own strategy on resolving `Git` conflicts faster and more easily.

**Comment by Osama-you** [comment]
I solved it
