### ISSUE TITLE
improper use of attributes on some tags

### ISSUE THREAD

**Issue by AhmedSafi97** [GSG-G9/MOYA-R--portfolio#22]
https://github.com/GSG-G9/MOYA-R--portfolio/blob/b7315896094eb11b143b4c8b1e3961759db10acc/index.html#L183

Attribute `alt` not allowed on element `a`. Check the attributes for `a` tag [here](https://www.w3schools.com/tags/tag_a.asp).

From your implementation, I guess you meant to use the `title` attribute to defines the title of the link but you confused it with the `alt` attribute, am I right?

**Comment by Osama-you** [comment]
I detect it using [https://validator.w3.org/](url) and I fixed it when I was working on fix-Stray-end-tag Relates #20
